language: julia
os:
  - linux
  - osx
julia:
  - 1.5
  - nightly
matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true
notifications:
  email: false
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage")'
  - julia -e 'using Coverage; Codecov.submit(process_folder())'
